source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Ouroboros_Example', :exclusive => true do
  pod "Ouroboros", :path => "../"
end

target 'Ouroboros_Tests', :exclusive => true do
  pod "Ouroboros", :path => "../"

  
end
